### PR TITLE
refactored some code

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
just removed some for loops, since they were identical

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
Oh hello!
Didn't think you would actually merge this...

Anyways, would it be okay to ask for some assistance in patching the game?

I am working on a server emulator, basically a server but without any actual tcp packets, directly communicating with the game.

The thing is, I can't get it to work, that is because I cannot trigger the events EagleTcp produces.

My initial thought was to patch the parseCmd method which is responsible for "fetching" packets so that ParseCmd which calls parseCmd will work as intended and trigger the events, but it doesn't work.

I can happily make a repo of what I've done so far and give you access if you do accept to help me.

I did try to modify your hook, but it did not work as well.

**Comment by ArjixWasTaken** [comment]
Here is how I intercept the outgoing calls:
image

And here is my attempt at patching `parseCmd`:
image
image

**Comment by ArjixWasTaken** [comment]
Deleted my request for help, as I did manage to do what I wanted.

**Comment by MoeGrid** [comment]
可以看看我的另一个项目，这是我用nodejs实现的一个服务器。
(You can check out another project of mine, which is a server I implemented in nodejs.)

[https://github.com/MoeGrid/invaxion-server](https://github.com/MoeGrid/invaxion-server)

因为我的时间比较少，所以无法继续开发。下面这个项目是根据我的代码继续开发的。这个项目目前已上线运行。
(Since I have less time, I can't continue the development. The following project is based on my code to continue the development. This project is currently up and running.)

[https://github.com/603185423/invaxion-server.git](https://github.com/603185423/invaxion-server.git)

**Pull request merged**
